### PR TITLE
Fix row conversion test

### PR DESCRIPTION
**Pull request by ttnghia**
This is a temporary workaround to fix https://github.com/NVIDIA/spark-rapids-jni/issues/1567.

### CODE REVIEW

**Comment by ttnghia** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
re-trigger to get a faster node for premerge. the previous one has a super slow CPU for compiling

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]
passed the test.
@ttnghia are we OK to merge this one first to unblock other changes first?

**Comment by ttnghia** [comment]
Sure. Please go ahead.

**Comment by ttnghia** [comment]
Done.

**Pull request merged**
