### PR TITLE
[submodule-sync] bot-submodule-sync-branch-24.04 to branch-24.04 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 337f0809348e1d1a88f614de859b3908d3111087, cudf commit SHA: https://github.com/rapidsai/cudf/commit/b08dd9bed15e60d86a561fc0cb47cdbc2428a09b

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 337f0809348e1d1a88f614de859b3908d3111087, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b08dd9bed15e60d86a561fc0cb47cdbc2428a09b
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 337f0809348e1d1a88f614de859b3908d3111087, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b08dd9bed15e60d86a561fc0cb47cdbc2428a09b
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 337f0809348e1d1a88f614de859b3908d3111087, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b08dd9bed15e60d86a561fc0cb47cdbc2428a09b
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 337f0809348e1d1a88f614de859b3908d3111087, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b08dd9bed15e60d86a561fc0cb47cdbc2428a09b
Test passed: **False**

**Comment by abellina** [comment]
Broken due to cuDF change around how NVTX is included:

> [INFO]      [exec] CMake Error: install(EXPORT "cudf-exports" ...) includes target "cudf" which requires target "nvtx3-cpp" that is not in any export set.
[INFO]      [exec] CMake Error in CMakeLists.txt:
[INFO]      [exec]   export called with target "cudf" which requires target "nvtx3-cpp" that is
[INFO]      [exec]   not in any export set.


I tried following the recommendation in the PR (https://github.com/rapidsai/cudf/pull/15178) to add `nvtx3-cpp` explicitly to our targets but it doesn't seem to work. 

```
diff --git a/src/main/cpp/CMakeLists.txt b/src/main/cpp/CMakeLists.txt
index 3baf384..46e7d6f 100644
--- a/src/main/cpp/CMakeLists.txt
+++ b/src/main/cpp/CMakeLists.txt
@@ -96,6 +96,8 @@ include(cmake/Modules/ConfigureCUDA.cmake) # set other CUDA compilation flags
 
 # find CCCL
 include(${CUDF_DIR}/cpp/cmake/thirdparty/get_cccl.cmake)
+# find NVTX
+include(${CUDF_DIR}/cpp/cmake/thirdparty/get_nvtx.cmake)
 
 # JNI
 find_package(JNI REQUIRED)
@@ -220,7 +222,7 @@ if(CUDF_USE_PER_THREAD_DEFAULT_STREAM)
 endif()
 
 target_link_libraries(
-  spark_rapids_jni PRIVATE
+  spark_rapids_jni PRIVATE nvtx3-cpp
   -Wl,--whole-archive
     ${CUDFJNI_LIB}
     cudf::cudf
@@ -258,7 +260,7 @@ if(USE_GDS)
                CXX_STANDARD_REQUIRED ON
   )
   target_link_libraries(
-    cufilejni PRIVATE
+    cufilejni PRIVATE nvtx3-cpp
     -Wl,--whole-archive
       ${CUFILEJNI_LIB}
     -Wl,--no-whole-archive
```

**Comment by nvauto** [comment]
HEAD commit SHA: 337f0809348e1d1a88f614de859b3908d3111087, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b08dd9bed15e60d86a561fc0cb47cdbc2428a09b
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 337f0809348e1d1a88f614de859b3908d3111087, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b08dd9bed15e60d86a561fc0cb47cdbc2428a09b
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 359bb80eab1434e2254325dedc8fdd2b5f67e22a, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/6a03827a74aa820e4e9ad241b0bc0450ceb8c018
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 359bb80eab1434e2254325dedc8fdd2b5f67e22a, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/6a03827a74aa820e4e9ad241b0bc0450ceb8c018
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 359bb80eab1434e2254325dedc8fdd2b5f67e22a, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/6a03827a74aa820e4e9ad241b0bc0450ceb8c018
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b5530056d5a3434fef723a35338a5305ccece50b, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/dfaa41c28e27f54500cf41e91958528c8f883319
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: f26266e392188aba19912bc2b793248c6bb418f0, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/8ed3e20f3d800adde15c94799ac743ae52d251a6
Test passed: **True**

**Comment by nvauto** [comment]
**SUCCESS** - auto-merge

**Pull request merged**
