### PR TITLE
[submodule-sync] bot-submodule-sync-branch-24.04 to branch-24.04 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 981aadaab87f33c4d9662cde7c3fd286de367986, cudf commit SHA: https://github.com/rapidsai/cudf/commit/e612a8aee5ba54f397b8d5be14201776bac9dd2d

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 981aadaab87f33c4d9662cde7c3fd286de367986, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/e612a8aee5ba54f397b8d5be14201776bac9dd2d
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 7b2cd8d151c14222c08e82bf3510470f19b7b400, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/dbf7236c4b30ee6f87223b728688cddf39453d14
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 7b2cd8d151c14222c08e82bf3510470f19b7b400, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/dbf7236c4b30ee6f87223b728688cddf39453d14
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: c42d2a28b2416ab85e3b77f728325d85f0a69891, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/bb0e4fdd6f4960d1d5125256dc147f28d83db560
Test passed: **False**

**Review by ttnghia — APPROVED** [review]

**Pull request merged**
