### PR TITLE
get-json-object:  Add JSON parser and parser utility

### PR DESCRIPTION
**Pull request by res-life**
closes https://github.com/NVIDIA/spark-rapids-jni/issues/1827
closes https://github.com/NVIDIA/spark-rapids-jni/issues/1829

- Add JSON parser
- JSON parser utility: copy_raw_text, skip_children
- Define internal interfaces for JSON generator, JSON parser, JSON path parser
- Copy get-json-obj CUDA code from cuDF

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
Epic issue is: https://github.com/NVIDIA/spark-rapids-jni/issues/1823

Add JSON parser.
Define interfaces for JSON generator, JSON parser, JSON path parser.

The last spark-rapids-jni buiding failed in CI. So I used a previous commit: 9274bd5d01d9d456b18dd3843c7f304ecfc1ac6b
I compiled this PR successfully based on reversion 9274bd5d01d9d456b18dd3843c7f304ecfc1ac6b.

Haoyang will implement JSON path parser.
Suraj will implement JSON generator parser.

We will post several PRs to facilitate review process.
In the end, after tested get-json-object totally successfully, then enable these PRs.

How to enable these PRs: just change the JNI code to call new get-json-object.

**Comment by res-life** [comment]
@revans2  Help to review.

**Review by revans2 — COMMENTED** [review]
In general it looks good, but we need to finish the TODOs and add in JNI APIs.

**Comment by res-life** [comment]
I created a new branch: [NVIDIA:get-json-object-feature](https://github.com/NVIDIA/spark-rapids-jni/tree/get-json-object-feature)

Let's use this feature branch to merge code, thanks.
Help review.

@thirtiseven  @SurajAralihalli  Let's use new feature branch to implement.
Please use this new feature branch to post PR.

**Review by revans2 — APPROVED** [review]
Most of this looks fine to me, but there are so many TODOs in the code I don't know if this is really ready to go or not, or really how to evaluate what is here.

**Pull request merged**
