### PR TITLE
Download boost package for CI jobs

### PR DESCRIPTION
**Pull request by NvTimLiu**
To fix: https://github.com/NVIDIA/spark-rapids-jni/issues/1671

The old Boost package URL is frequently not available to build CI Docker container. [boost_1_79_0.tar.gz] (https://github.com/NVIDIA/spark-rapids-jni/blob/branch-24.02/ci/Dockerfile#L64).

Update the Boost linkage for CI scripts, to PASS the spark-rapids-jni nightly build/test CI jobs.

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by jlowe — COMMENTED** [review]
2024 copyrights, otherwise lgtm.

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
Oh as the boost linkage is available again: https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz

CLOSE the PR,

**Comment by NvTimLiu** [comment]
The old boost linkage is not stable :  https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz

![Uploading image.png…]

Change to use the new stable linkage URL

**Review by gerashegalov — APPROVED** [review]
LGTM

**Pull request merged**
