### PR TITLE
Update JNI build to support nvcomp4

### PR DESCRIPTION
**Pull request by pxLi**
depends on https://github.com/rapidsai/cudf/pull/16076

**NOTE:** We must update the submodule ref in this change once above gets merged.

### CODE REVIEW

**Comment by pxLi** [comment]
re-target to 24.10 and waiting for cudf updates

**Comment by pxLi** [comment]
will update to include change at https://github.com/rapidsai/cudf/pull/16076

**Comment by bdice** [comment]
@pxLi The cuDF work to support nvcomp 4.0.1 is now complete: https://github.com/rapidsai/cudf/pull/16076

This should be ready to update the submodule ref now.

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
