### PR TITLE
[submodule-sync] bot-submodule-sync-branch-24.04 to branch-24.04 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 3984c817273a910ddbead96584b2a7897cb05a2a, cudf commit SHA: https://github.com/rapidsai/cudf/commit/2b57c610ddf75ec0e87e6edabd455e998a0371de

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 3984c817273a910ddbead96584b2a7897cb05a2a, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/2b57c610ddf75ec0e87e6edabd455e998a0371de
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 3984c817273a910ddbead96584b2a7897cb05a2a, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/2b57c610ddf75ec0e87e6edabd455e998a0371de
Test passed: **False**

**Comment by jlowe** [comment]
Workinig on this

**Comment by nvauto** [comment]
HEAD commit SHA: 886067b3cf31169d618ec87300b7b6547ef0e120, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ee3c7699bbae4955e68abd13a522ba87c9ffd28c
Test passed: **False**

**Pull request closed without merging**
