### PR TITLE
Inline build-libcudf and simplify overall build

### PR DESCRIPTION
**Pull request by gerashegalov**
Additional changes 
- Deprecate libcudf.clean.skip. Default it to `false`
- Move libcudf build to target/libcudf/cmake-build
- Move jni build to target/jni/cmake-build
- Reduce relative path hard-coding
- Introduce BUILD_CUDF_TESTS/BENCHMARKS
- Skip native tests when -DskipTests is passed

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
