### PR TITLE
[submodule-sync] bot-submodule-sync-branch-24.06 to branch-24.06 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 3f0589fa479f993f3f9b59343bcd4601f6b17858, cudf commit SHA: https://github.com/rapidsai/cudf/commit/4e44d5d3c80852a15ae28d5afa0b13646ca3a4fd

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 3f0589fa479f993f3f9b59343bcd4601f6b17858, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/4e44d5d3c80852a15ae28d5afa0b13646ca3a4fd
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: ba3505f890998b2cef86b9866644abe70e14d7da, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/a00c3c916947d16fbf997095a32a02ca510b78e5
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: ba3505f890998b2cef86b9866644abe70e14d7da, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/a00c3c916947d16fbf997095a32a02ca510b78e5
Test passed: **False**

**Comment by ttnghia** [comment]
build

**Comment by nvauto** [comment]
HEAD commit SHA: 78ec2b7a99886ac5af3f060854510eed09ef8548, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/6319ab708f2dff9fd7a62a5c77fd3b387bde1bb8
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: e72eb95d5f9d039ab387acba6b042c941c82ab57, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c5eb3240387222373043ddf881d18fb5d18e0834
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: e72eb95d5f9d039ab387acba6b042c941c82ab57, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c5eb3240387222373043ddf881d18fb5d18e0834
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: e72eb95d5f9d039ab387acba6b042c941c82ab57, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c5eb3240387222373043ddf881d18fb5d18e0834
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: e72eb95d5f9d039ab387acba6b042c941c82ab57, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c5eb3240387222373043ddf881d18fb5d18e0834
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: e72eb95d5f9d039ab387acba6b042c941c82ab57, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c5eb3240387222373043ddf881d18fb5d18e0834
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: e72eb95d5f9d039ab387acba6b042c941c82ab57, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c5eb3240387222373043ddf881d18fb5d18e0834
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 1a6b0a2441188bb8ef4a143a6cc19688a242c40f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c5eb3240387222373043ddf881d18fb5d18e0834
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: d26779cf108755e4b7017644d38fe5504dbae4d2, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/6c31eacce54d8f1c9d3ad183d8879e09e679b369
Test passed: **True**

**Comment by nvauto** [comment]
**SUCCESS** - auto-merge

**Pull request merged**
