### PR TITLE
[submodule-sync] bot-submodule-sync-branch-23.06 to branch-23.06 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: b55db80ae707065e2ca0fb464619e87718f61705, cudf commit SHA: https://github.com/rapidsai/cudf/commit/daf3ac0cfd538f6e5d63e3064c71b96076b1e530

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: b55db80ae707065e2ca0fb464619e87718f61705, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/daf3ac0cfd538f6e5d63e3064c71b96076b1e530
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b821b34c78f3fccffd7b22ae40877069cf6a852f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/0b59fdad43fa5fd35287748a57d800e8db37c416
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b821b34c78f3fccffd7b22ae40877069cf6a852f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/0b59fdad43fa5fd35287748a57d800e8db37c416
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b821b34c78f3fccffd7b22ae40877069cf6a852f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/0b59fdad43fa5fd35287748a57d800e8db37c416
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b821b34c78f3fccffd7b22ae40877069cf6a852f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/0b59fdad43fa5fd35287748a57d800e8db37c416
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 8f33e72d81b8208556706857fc49f8849d799d5f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/580ee40bf5fe1a66eaba914cdddb718a09193bab
Test passed: **False**

**Comment by pxLi** [comment]
```
11:12:45  [INFO]      [exec] [ 91%] Built target cufilejni
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp: In member function 'virtual void StringToFloatTests_Simple_Test<gtest_TypeParam_>::TestBody()':
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp:578:26: error: no matching function for call to 'cudf::column::set_null_mask(std::pair<rmm::device_buffer, int>)'
11:12:45  [INFO]      [exec]   578 |   expected->set_null_mask(
11:12:45  [INFO]      [exec]       |   ~~~~~~~~~~~~~~~~~~~~~~~^
11:12:45  [INFO]      [exec]   579 |     cudf::test::detail::make_null_mask(valid_iter, valid_iter + expected->size()));
11:12:45  [INFO]      [exec]       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:12:45  [INFO]      [exec] In file included from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf_test/column_wrapper.hpp:19,
11:12:45  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp:20:
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:194:8: note: candidate: 'void cudf::column::set_null_mask(rmm::device_buffer&&, cudf::size_type)'
11:12:45  [INFO]      [exec]   194 |   void set_null_mask(rmm::device_buffer&& new_null_mask,
11:12:45  [INFO]      [exec]       |        ^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:194:43: note:   no known conversion for argument 1 from 'std::pair<rmm::device_buffer, int>' to 'rmm::device_buffer&&'
11:12:45  [INFO]      [exec]   194 |   void set_null_mask(rmm::device_buffer&& new_null_mask,
11:12:45  [INFO]      [exec]       |                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:212:8: note: candidate: 'void cudf::column::set_null_mask(const rmm::device_buffer&, cudf::size_type, rmm::cuda_stream_view)'
11:12:45  [INFO]      [exec]   212 |   void set_null_mask(rmm::device_buffer const& new_null_mask,
11:12:45  [INFO]      [exec]       |        ^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:212:48: note:   no known conversion for argument 1 from 'std::pair<rmm::device_buffer, int>' to 'const rmm::device_buffer&'
11:12:45  [INFO]      [exec]   212 |   void set_null_mask(rmm::device_buffer const& new_null_mask,
11:12:45  [INFO]      [exec]       |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp: In member function 'virtual void StringToFloatTests_InfNaN_Test<gtest_TypeParam_>::TestBody()':
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp:595:26: error: no matching function for call to 'cudf::column::set_null_mask(std::pair<rmm::device_buffer, int>)'
11:12:45  [INFO]      [exec]   595 |   expected->set_null_mask(
11:12:45  [INFO]      [exec]       |   ~~~~~~~~~~~~~~~~~~~~~~~^
11:12:45  [INFO]      [exec]   596 |     cudf::test::detail::make_null_mask(valid_iter, valid_iter + expected->size()));
11:12:45  [INFO]      [exec]       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:12:45  [INFO]      [exec] In file included from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf_test/column_wrapper.hpp:19,
11:12:45  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp:20:
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:194:8: note: candidate: 'void cudf::column::set_null_mask(rmm::device_buffer&&, cudf::size_type)'
11:12:45  [INFO]      [exec]   194 |   void set_null_mask(rmm::device_buffer&& new_null_mask,
11:12:45  [INFO]      [exec]       |        ^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:194:43: note:   no known conversion for argument 1 from 'std::pair<rmm::device_buffer, int>' to 'rmm::device_buffer&&'
11:12:45  [INFO]      [exec]   194 |   void set_null_mask(rmm::device_buffer&& new_null_mask,
11:12:45  [INFO]      [exec]       |                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:212:8: note: candidate: 'void cudf::column::set_null_mask(const rmm::device_buffer&, cudf::size_type, rmm::cuda_stream_view)'
11:12:45  [INFO]      [exec]   212 |   void set_null_mask(rmm::device_buffer const& new_null_mask,
11:12:45  [INFO]      [exec]       |        ^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:212:48: note:   no known conversion for argument 1 from 'std::pair<rmm::device_buffer, int>' to 'const rmm::device_buffer&'
11:12:45  [INFO]      [exec]   212 |   void set_null_mask(rmm::device_buffer const& new_null_mask,
11:12:45  [INFO]      [exec]       |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp: In member function 'virtual void StringToFloatTests_InvalidValues_Test<gtest_TypeParam_>::TestBody()':
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp:612:26: error: no matching function for call to 'cudf::column::set_null_mask(std::pair<rmm::device_buffer, int>)'
11:12:45  [INFO]      [exec]   612 |   expected->set_null_mask(
11:12:45  [INFO]      [exec]       |   ~~~~~~~~~~~~~~~~~~~~~~~^
11:12:45  [INFO]      [exec]   613 |     cudf::test::detail::make_null_mask(valid_iter, valid_iter + expected->size()));
11:12:45  [INFO]      [exec]       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:12:45  [INFO]      [exec] In file included from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf_test/column_wrapper.hpp:19,
11:12:45  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/tests/cast_string.cpp:20:
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:194:8: note: candidate: 'void cudf::column::set_null_mask(rmm::device_buffer&&, cudf::size_type)'
11:12:45  [INFO]      [exec]   194 |   void set_null_mask(rmm::device_buffer&& new_null_mask,
11:12:45  [INFO]      [exec]       |        ^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:194:43: note:   no known conversion for argument 1 from 'std::pair<rmm::device_buffer, int>' to 'rmm::device_buffer&&'
11:12:45  [INFO]      [exec]   194 |   void set_null_mask(rmm::device_buffer&& new_null_mask,
11:12:45  [INFO]      [exec]       |                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:212:8: note: candidate: 'void cudf::column::set_null_mask(const rmm::device_buffer&, cudf::size_type, rmm::cuda_stream_view)'
11:12:45  [INFO]      [exec]   212 |   void set_null_mask(rmm::device_buffer const& new_null_mask,
11:12:45  [INFO]      [exec]       |        ^~~~~~~~~~~~~
11:12:45  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column.hpp:212:48: note:   no known conversion for argument 1 from 'std::pair<rmm::device_buffer, int>' to 'const rmm::device_buffer&'
11:12:45  [INFO]      [exec]   212 |   void set_null_mask(rmm::device_buffer const& new_null_mask,
11:12:45  [INFO]      [exec]       |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
11:12:50  [INFO]      [exec] gmake[2]: *** [tests/CMakeFiles/CAST_STRING.dir/build.make:76: tests/CMakeFiles/CAST_STRING.dir/cast_string.cpp.o] Error 1
11:12:50  [INFO]      [exec] gmake[1]: *** [CMakeFiles/Makefile2:976: tests/CMakeFiles/CAST_STRING.dir/all] Error 2
11:12:50  [INFO]      [exec] gmake[1]: *** Waiting for unfinished jobs....
11:13:05  [INFO]      [exec] [ 95%] Linking CXX executable ../gtests/ROW_CONVERSION
11:13:06  [INFO]      [exec] [ 95%] Built target ROW_CONVERSION
11:13:06  [INFO]      [exec] gmake: *** [Makefile:146: all] Error 2
11:13:06  [INFO] ------------------------------------------------------------------------
11:13:06  [INFO] BUILD FAILURE
```

**Comment by nvauto** [comment]
HEAD commit SHA: 6bd47047977cfdc921904909821e688156ced24c, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/a6fb6a2b615c25ed34a46f1da311d13c78db63c3
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 6bd47047977cfdc921904909821e688156ced24c, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/a6fb6a2b615c25ed34a46f1da311d13c78db63c3
Test passed: **False**

**Comment by jlowe** [comment]
make_null_mask return value was changed in rapidsai/cudf#13081, need to update our test code accordingly.

**Comment by jlowe** [comment]
Will be fixed by #1081.

**Pull request closed without merging**
