### PR TITLE
[submodule-sync] bot-submodule-sync-branch-24.06 to branch-24.06 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 592c67c704c4fed71e875c8cf1cdba3a9f829245, cudf commit SHA: https://github.com/rapidsai/cudf/commit/bd93e203b0bdfaa2b736a385ea7595c904bd30d8

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 592c67c704c4fed71e875c8cf1cdba3a9f829245, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/bd93e203b0bdfaa2b736a385ea7595c904bd30d8
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b40e539a8dab79449003aa523f18b41ac15d801f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/65a51ffa364b8a54fadab041cb5c563873303643
Test passed: **False**

**Comment by NvTimLiu** [comment]
The submodule build has FAILED. Please wait for the next sync, and it should PASS.

**Comment by nvauto** [comment]
HEAD commit SHA: b40e539a8dab79449003aa523f18b41ac15d801f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/65a51ffa364b8a54fadab041cb5c563873303643
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b40e539a8dab79449003aa523f18b41ac15d801f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/65a51ffa364b8a54fadab041cb5c563873303643
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b40e539a8dab79449003aa523f18b41ac15d801f, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/65a51ffa364b8a54fadab041cb5c563873303643
Test passed: **False**

**Comment by jlowe** [comment]
Blocked by failures to configure arrow for static linking after the recent arrow upgrade in cudf.  Tracked by rapidsai/cudf#15714.

**Comment by nvauto** [comment]
HEAD commit SHA: 0c397ca8e14b8a27204e737d887eb5274c436804, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b810113d6255dbe123aafbc80018bf6165a0842f
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 58fc87c3879b5817eb9a44c00845313be34c389d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b5a9c4b5114390fb45e27d9aab5eaa995de3fa37
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: f9725460814bb378b768d6ca6da7ce31003ad702, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ce1933fc07d5f8d1da3ad36217ea0b39d7a926fa
Test passed: **False**

**Comment by NvTimLiu** [comment]
Blocked on https://github.com/rapidsai/cudf/issues/15714

**Comment by nvauto** [comment]
HEAD commit SHA: f9725460814bb378b768d6ca6da7ce31003ad702, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ce1933fc07d5f8d1da3ad36217ea0b39d7a926fa
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: f9725460814bb378b768d6ca6da7ce31003ad702, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ce1933fc07d5f8d1da3ad36217ea0b39d7a926fa
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: f9725460814bb378b768d6ca6da7ce31003ad702, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ce1933fc07d5f8d1da3ad36217ea0b39d7a926fa
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: f9725460814bb378b768d6ca6da7ce31003ad702, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ce1933fc07d5f8d1da3ad36217ea0b39d7a926fa
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: dd5fffa1a1bfcc8b0439a3af62d1214fc056a5d6, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/425a5dac64b7c74c061b588dc8725c5390517cf9
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 272a04e6769983b2a1f366b9ffbd17495a5d39e5, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b4bdea295331862949afe408feb47522a4ff8f2a
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: f9c0c32ecce4778544bc807ce5e2baa9490cb079, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c42c4189d3273205a75d7b3c3ab33446eefb7631
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 327fdb61ce81d6c74c3c180e600cdd7665e6761a, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/915c6bea2069f75b5637ff39befd877ba37a1922
Test passed: **False**

**Pull request closed without merging**
