### PR TITLE
Fix performance regression of `get_json_object` due to unnecessary stream synchronization

### PR DESCRIPTION
**Pull request by ttnghia**
After a stream sync added in https://github.com/NVIDIA/spark-rapids-jni/pull/2266, the performance of `get_json_object` surprisingly drops by more than 10%. This PR removes that stream sync by combining the error check values together and only synchronizing stream just once.

### CODE REVIEW

**Comment by ttnghia** [comment]
build

**Comment by ttnghia** [comment]
build

**Comment by ttnghia** [comment]
build

**Comment by ttnghia** [comment]
build

**Comment by revans2** [comment]
I just ran performance and correctness tests and it looks good. If anything it is slightly faster than before. I want to rerun with the latest merge changes you put in too. But that should only be a few more mins

**Comment by ttnghia** [comment]
build

**Comment by ttnghia** [comment]
build

**Review by revans2 — APPROVED** [review]
The performance looks good and all of my tests passed.

**Pull request merged**
