### PR TITLE
Merge branch 22.10 to branch 22.12

### PR DESCRIPTION
**Pull request by pxLi**
as title. Since automerge currently blocked by permission issue, we manually file PR to merge

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Review by GaryShen2008 — APPROVED** [review]

**Comment by pxLi** [comment]
err my bad, forget to merge as a merge commit. Will file a new one to include commit history

**Pull request merged**
