### PR TITLE
Pre-commit formatting pass on cpp files.

### PR DESCRIPTION
**Pull request by nvdbaranec**
We were behind a bit. Quite a few files got reformatted.

### CODE REVIEW

**Review by revans2 — DISMISSED** [review]
At least it is consistent in how it looks. Really confused by a lot of the formatting choices, but I am not up for a war on any of this.

**Comment by ttnghia** [comment]
There is no `.clang-format` config for this repository. Can you provide that file please?

**Comment by gerashegalov** [comment]
> There is no `.clang-format` config for this repository. Can you provide that file please?

If pre-commit is used we use cudf's https://github.com/NVIDIA/spark-rapids-jni/blob/branch-23.08/.pre-commit-config.yaml#L10

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by ttnghia** [comment]
That's great, so we can reuse cudf C++ config. And we should do the same for the C++ files in cudf Java folder.

**Comment by hyperbolic2346** [comment]
We should automate this or enforce it in CI.

**Comment by ttnghia** [comment]
I would suggest to create symbolic link to cudf config file so our IDE can find it automatically.

**Comment by bdice** [comment]
@nvdbaranec FYI, the clang-format version defined in `.pre-commit-config.yaml` is major version 14, not the same as what cudf uses (16.0.1).

**Comment by gerashegalov** [comment]
> We should automate this or enforce it in CI.

The main purpose of auto-formatting is to remove to the overhead of code-formatting discussions on the PR's. I have been +1 on this. CI does not solve this problem. The pre-commit hook does. Last time it came up,  there was no consensus. If it changes we can enforce it by requiring a github action of applying that pre-commit check to succeed without a diff.

**Comment by nvdbaranec** [comment]
Updated config version as per @bdice 's suggestion.

**Comment by bdice** [comment]
Regarding automatic enforcement CI: running pre-commit in CI is how RAPIDS solves this, because it forces local commits and CI builds to adhere to the same rules. See https://github.com/rapidsai/cudf/blob/branch-23.08/ci/check_style.sh for cudf’s script.

**Comment by gerashegalov** [comment]
> Regarding automatic enforcement CI: running pre-commit in CI is how RAPIDS solves this, because it forces local commits and CI builds to adhere to the same rules. See https://github.com/rapidsai/cudf/blob/branch-23.08/ci/check_style.sh for cudf’s script.

this looks exactly like the CI-based based PR check I [described](https://github.com/NVIDIA/spark-rapids-jni/pull/1244#issuecomment-1614985713) , which could run as a github action 

I may have misunderstood @hyperbolic2346  comment assuming it's about a job that periodically reformats and

**Review by gerashegalov — APPROVED** [review]

**Review by jlowe — COMMENTED** [review]
Changes look OK other than it needs a [signoff commit per contributor guidelines](https://github.com/NVIDIA/spark-rapids-jni/blob/branch-23.08/CONTRIBUTING.md#sign-your-work).

**Comment by jlowe** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
