### PR TITLE
Merge branch 'branch-23.06' into main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge branch 'branch-23.06' into main

Change version to v23.06.0 for release

Note: merge the PR with `Create a new merge commit`
    
Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
The PR is for in-advance reviews to unblock release plan.

We will merge all following changes later if any, thanks!

**Comment by pxLi** [comment]
I will update submodule ref to cudf release tag when available, thanks

**Review by jlowe — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
Let's skip ci, as the last [PR1201](https://github.com/NVIDIA/spark-rapids-jni/pull/1201) passed CI build

**Review by pxLi — APPROVED** [review]

**Pull request merged**
