### PR TITLE
Merge branch 'branch-23.08' into main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge branch 'branch-23.08' into main

Change version to v23.08.0

Signed-off-by: Tim Liu <timl@nvidia.com>

**NOTE:  merge this PR via "Create a merge commit"**

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
We will update cudf submodule to released tag when available later this week.

This change is for in-advance commit history review, thanks!

**Review by jlowe — APPROVED** [review]
Other than the pending cudf submodule commit, lgtm.

**Review by ttnghia — APPROVED** [review]

**Review by pxLi — APPROVED** [review]
Please upmerge the PR to latest, and merge the change as `Create a merge commit`

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
