### PR TITLE
[submodule-sync] bot-submodule-sync-branch-22.04 to branch-22.04 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: b2019790806492bcd152eb08dae728bca51e8769, cudf commit SHA: https://github.com/rapidsai/cudf/commit/a552afb88c6496814326651555bb9dde2a87028d

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: b2019790806492bcd152eb08dae728bca51e8769, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/a552afb88c6496814326651555bb9dde2a87028d
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: b2019790806492bcd152eb08dae728bca51e8769, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/a552afb88c6496814326651555bb9dde2a87028d
Test passed: **True**

**Comment by nvauto** [comment]
**SUCCESS** - auto-merge

**Comment by pxLi** [comment]
previous failure was due to `ai.rapids.cudf.CudaException: system has unsupported display driver / cuda driver combination`

applied compatible resolver patch to the internal pipeline

**Pull request merged**
