### PR TITLE
Initiate Version 24.02.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
Init project version 24.02.0-SNAPSHOT
Update cudf submodule targeting https://github.com/rapidsai/cudf/tree/branch-24.02

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
confirmed currently 23.04 rapids build could not pass correctly. 
We will update submodule commit to latest and retry next week after their burndown end (this Friday)

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
currently blocked by https://github.com/NVIDIA/spark-rapids-jni/issues/1567

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
