### PR TITLE
Pin cudf dependencies during build

### LINKED ISSUE #1666: [BUG] The build can be broken due to dependency changes of cudf
**Describe the bug**
The cudf build always grabs the [latest RMM](https://github.com/rapidsai/rapids-cmake/blob/c9a3eeb4b291806b9aa940ed7e3ff4a5a30fe907/rapids-cmake/cpm/versions.json#L86) of a specific branch to build. This can and has caused build breakages as the RMM may not be compatible with the cudf version. Most recently, this was the CCCL 2.2 change that hit RMM and cudf at the same time. We pin a specific cudf commit, so our cudf didn't move forward, but RMM was pulled from latest and so it was using CCCL 2.2. This resulted in builds failing even though we had a pinned cudf commit.

**Steps/Code to reproduce bug**
Sync to a commit of spark-rapids-jni before the CCCL 2.2 changes were merged and build.

**Expected behavior**
We run CI and put a specific cudf commit into the submodule to prevent breakages like this. We should be able to continue using the toolchain from the time of the CI build.

**Additional context**
Bradley proposed a fix by creating a `versions.json` file that can be used with [rapids cpm package override](https://docs.rapids.ai/api/rapids-cmake/stable/command/rapids_cpm_package_override/) to pin to the versions that we actually used to build and test in CI. This leaves cmake itself as the only wildcard. This [can also be pinned](https://github.com/rapidsai/rapids-cmake/blob/branch-24.02/README.md#overriding-rapidscmake) to a specific git SHA.

### PR DESCRIPTION
**Pull request by jlowe**
Closes #1666.  This restores the changes from #1877 and updates the rapids-cmake version to avoid the issue reported in NVIDIA/spark-rapids#10627.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
Verified RAPIDS Accelerator zstd tests pass with this build.

**Review by gerashegalov — DISMISSED** [review]
LGTM

**Review by ttnghia — COMMENTED** [review]
Does this mean we always pin, and we have to manually upgrade after a while?

**Comment by jlowe** [comment]
> Does this mean we always pin, and we have to manually upgrade after a while?

No.  There's two modes to the build.  The default is to use the pinned versions, but the submodule sync build, which automatically runs every few hours, will build in a mode that updates the pinned versions file to whatever versions it finds when it moves to the updated cudf version.  See https://github.com/NVIDIA/spark-rapids-jni/pull/1901/files#diff-a4b52f1881e34609ce5cd5e0722da2f2f708d1eef03334723a5628082fe94d31

**Comment by jlowe** [comment]
I just realized I should update this PR to refresh the pin versions, since it's been almost a week since those were updated in this PR.  Should have that updated shortly.

**Comment by jlowe** [comment]
build

**Review by ttnghia — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]

**Comment by bdice** [comment]
@jlowe This is awesome! I'm really glad this approach worked out.

**Comment by jlowe** [comment]
Thank @bdice, but all the credit goes to @robertmaynard for the idea and implementation.

**Pull request merged**
