### PR TITLE
Variable 'USE_GDS' to support build on arm CPU [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Overwrite  `USE_GDS=OFF` on arm CPU

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Review by pxLi — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
nightly script may just `skip ci`

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Pull request merged**
