### PR TITLE
[submodule-sync] bot-submodule-sync-branch-23.06 to branch-23.06 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: d49434a6a418da938b5c4799e6fc507d9739cff6, cudf commit SHA: https://github.com/rapidsai/cudf/commit/b22f68efd752c15dffbddca233b0c75cbddc5318

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: d49434a6a418da938b5c4799e6fc507d9739cff6, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b22f68efd752c15dffbddca233b0c75cbddc5318
Test passed: **False**

**Comment by pxLi** [comment]
```
10:58:51  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/src/SparkResourceAdaptorJni.cpp: In function 'auto {anonymous}::make_logger(const string&)':
10:58:51  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/src/SparkResourceAdaptorJni.cpp:108:39: error: 'basic_file_sink_mt' is not a member of 'spdlog::sinks'
10:58:51  [INFO]      [exec]   108 |       std::make_shared<spdlog::sinks::basic_file_sink_mt>(filename, true /*truncate file*/));
10:58:51  [INFO]      [exec]       |                                       ^~~~~~~~~~~~~~~~~~
10:58:51  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/src/SparkResourceAdaptorJni.cpp:108:58: error: no matching function for call to 'make_shared<<expression error> >(const string&, bool)'
10:58:51  [INFO]      [exec]   108 |       std::make_shared<spdlog::sinks::basic_file_sink_mt>(filename, true /*truncate file*/));
10:58:51  [INFO]      [exec]       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:58:51  [INFO]      [exec] In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/memory:77,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/rmm/detail/aligned.hpp:22,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/rmm/mr/device/device_memory_resource.hpp:19,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/rmm/device_buffer.hpp:20,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/utilities/span.hpp:19,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/column/column_view.hpp:20,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/libcudf-install/include/cudf/copying.hpp:19,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/cmake-build/../../thirdparty/cudf/java/src/main/native/src/cudf_jni_apis.hpp:18,
10:58:51  [INFO]      [exec]                  from /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/src/SparkResourceAdaptorJni.cpp:24:
10:58:51  [INFO]      [exec] /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/shared_ptr.h:875:5: note: candidate: 'template<class _Tp, class ... _Args> std::shared_ptr<_Tp> std::make_shared(_Args&& ...)'
10:58:51  [INFO]      [exec]   875 |     make_shared(_Args&&... __args)
10:58:51  [INFO]      [exec]       |     ^~~~~~~~~~~
10:58:51  [INFO]      [exec] /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/shared_ptr.h:875:5: note:   template argument deduction/substitution failed:
10:58:51  [INFO]      [exec] /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/src/main/cpp/src/SparkResourceAdaptorJni.cpp:108:58: error: template argument 1 is invalid
10:58:51  [INFO]      [exec]   108 |       std::make_shared<spdlog::sinks::basic_file_sink_mt>(filename, true /*truncate file*/));
10:58:51  [INFO]      [exec]       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:58:55  [INFO]      [exec] gmake[2]: *** [CMakeFiles/spark_rapids_jni.dir/build.make:146: CMakeFiles/spark_rapids_jni.dir/src/SparkResourceAdaptorJni.cpp.o] Error 1
10:58:55  [INFO]      [exec] gmake[2]: *** Waiting for unfinished jobs....
10:59:52  [INFO]      [exec] [ 62%] Linking CUDA shared library libcufaultinj.so
10:59:52  [INFO]      [exec] [ 62%] Built target cufaultinj
11:00:59  [INFO]      [exec] gmake[1]: *** [CMakeFiles/Makefile2:170: CMakeFiles/spark_rapids_jni.dir/all] Error 2
11:00:59  [INFO]      [exec] gmake: *** [Makefile:146: all] Error 2
```
failed spdlog usage

**Comment by nvauto** [comment]
HEAD commit SHA: 082fc3b2f5045339716833f1fcb96dcd3c107123, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/63f0b765a601256ea39a1f930fbf6eed38fe96d7
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 082fc3b2f5045339716833f1fcb96dcd3c107123, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/63f0b765a601256ea39a1f930fbf6eed38fe96d7
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 082fc3b2f5045339716833f1fcb96dcd3c107123, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/63f0b765a601256ea39a1f930fbf6eed38fe96d7
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: dcc573d33aa940f951c775aecc60bcbfd175a514, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c7f2342d2f740e21561c96cdaa687c497f86169a
Test passed: **True**

**Comment by nvauto** [comment]
**SUCCESS** - auto-merge

**Pull request merged**
