### PR TITLE
Merge 22.08 to main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge branch 'branch-22.08' into main, prepare for v22.08.0 release

**Merge this PR with "Create a merge request" instead of squash merge**

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
Please help review the commit history in advance, thanks

We will put a PR to update cudf submodule ref to tag v22.08.00 when its ready

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
https://github.com/NVIDIA/spark-rapids-jni/pull/490 will update the main branch to include the last submodule update after CI pass

**Review by pxLi — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
