### PR TITLE
[submodule-sync] bot-submodule-sync-branch-24.02 to branch-24.02 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 2b0d693138a568fc7870770006452500d6dc2b13, cudf commit SHA: https://github.com/rapidsai/cudf/commit/ac35d1950a8e34866706db10e627ef1a5a471e5d

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 2b0d693138a568fc7870770006452500d6dc2b13, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ac35d1950a8e34866706db10e627ef1a5a471e5d
Test passed: **False**

**Comment by pxLi** [comment]
```
04:57:15  [INFO]      [exec] In file included from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/fmt/fmt.h:31,
04:57:15  [INFO]      [exec]                  from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/common.h:50,
04:57:15  [INFO]      [exec]                  from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/spdlog.h:12,
04:57:15  [INFO]      [exec]                  from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/include/cudf/utilities/logger.hpp:19,
04:57:15  [INFO]      [exec]                  from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/include/cudf/detail/utilities/logger.hpp:19,
04:57:15  [INFO]      [exec]                  from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/src/io/utilities/config_utils.hpp:18,
04:57:15  [INFO]      [exec]                  from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/src/io/utilities/datasource.cpp:24:
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/fmt-src/include/fmt/core.h: In instantiation of 'constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = const cudaError; typename std::enable_if<PACKED, int>::type <anonymous> = 0]':
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/fmt-src/include/fmt/core.h:1808:51:   required from 'constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {const cudaError, const char*}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {cudaError, const char*}]'
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/fmt-src/include/fmt/core.h:1826:18:   required from 'constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = {const cudaError, const char*}]'
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/logger.h:374:75:   required from 'void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {const cudaError&, const char*}; spdlog::string_view_t = fmt::v10::basic_string_view<char>]'
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/logger.h:90:13:   required from 'void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::format_string<T ...>, Args&& ...) [with Args = {const cudaError&, const char*}; fmt::v10::format_string<T ...> = fmt::v10::basic_format_string<char, const cudaError&, const char*>]'
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/src/io/utilities/datasource.cpp:197:7:   required from here
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/fmt-src/include/fmt/core.h:1576:63: error: 'fmt::v10::detail::type_is_unformattable_for<const cudaError, char> _' has incomplete type
04:57:15  [INFO]      [exec]  1576 |     type_is_unformattable_for<T, typename Context::char_type> _;
04:57:15  [INFO]      [exec]       |                                                               ^
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/fmt-src/include/fmt/core.h:1580:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
04:57:15  [INFO]      [exec]  1580 |       formattable,
04:57:15  [INFO]      [exec]       |       ^~~~~~~~~~~
04:57:15  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-2450/thirdparty/cudf/cpp/build/_deps/fmt-src/include/fmt/core.h:1580:7: note: 'formattable' evaluates to false
04:57:16  [INFO]      [exec] gmake[2]: *** [CMakeFiles/cudf.dir/build.make:2752: CMakeFiles/cudf.dir/src/io/utilities/datasource.cpp.o] Error 1
04:57:16  [INFO]      [exec] gmake[2]: *** Waiting for unfinished jobs....
05:02:08  [INFO]      [exec] gmake[1]: *** [CMakeFiles/Makefile2:837: CMakeFiles/cudf.dir/all] Error 2
05:02:08  [INFO]      [exec] gmake: *** [Makefile:156: all] Error 2
```

**Comment by nvauto** [comment]
HEAD commit SHA: 2ae1abbf49578c2e2296d6c02edefb045158a8e9, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c8074b5176a74630101c78c43c24b66141352b24
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 2ae1abbf49578c2e2296d6c02edefb045158a8e9, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c8074b5176a74630101c78c43c24b66141352b24
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 2ae1abbf49578c2e2296d6c02edefb045158a8e9, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c8074b5176a74630101c78c43c24b66141352b24
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 2ae1abbf49578c2e2296d6c02edefb045158a8e9, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c8074b5176a74630101c78c43c24b66141352b24
Test passed: **False**

**Comment by jlowe** [comment]
Working on this

**Pull request closed without merging**
