### PR TITLE
Revert "Use ccache in build-in-docker by default"

### PR DESCRIPTION
**Pull request by gerashegalov**
Reverts NVIDIA/spark-rapids-jni#225 because it crossed with conflicting #199

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by gerashegalov** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
@gerashegalov looks like you forgot to approve duo push in time~

also, both pre-merge and nightly just started failing
```
[2022-05-06T22:50:48.563Z] [INFO]      [exec] -- Looking for _M_ARM64

[2022-05-06T22:50:48.824Z] [INFO]      [exec] -- Looking for _M_ARM64 - not found

[2022-05-06T22:50:48.824Z] [INFO]      [exec] -- Looking for __SIZEOF_INT128__

[2022-05-06T22:50:49.086Z] [INFO]      [exec] -- Looking for __SIZEOF_INT128__ - found

[2022-05-06T22:50:49.086Z] [INFO]      [exec] CMake Error at /usr/local/cmake-3.20.5-linux-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   Could NOT find Boost (missing: Boost_INCLUDE_DIR system filesystem)

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   (Required is at least version "1.58")

[2022-05-06T22:50:49.086Z] [INFO]      [exec] Call Stack (most recent call first):

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   /usr/local/cmake-3.20.5-linux-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   /usr/local/cmake-3.20.5-linux-x86_64/share/cmake-3.20/Modules/FindBoost.cmake:2345 (find_package_handle_standard_args)

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   build/_deps/arrow-src/cpp/cmake_modules/FindBoostAlt.cmake:48 (find_package)

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   build/_deps/arrow-src/cpp/cmake_modules/ThirdpartyToolchain.cmake:241 (find_package)

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   build/_deps/arrow-src/cpp/cmake_modules/ThirdpartyToolchain.cmake:956 (resolve_dependency)

[2022-05-06T22:50:49.086Z] [INFO]      [exec]   build/_deps/arrow-src/cpp/CMakeLists.txt:546 (include)
```

**Comment by pxLi** [comment]
build

**Pull request merged**
