### PR TITLE
[submodule-sync] bot-submodule-sync-branch-23.06 to branch-23.06 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 04a50c94c8691851d49303374f75f66cefc9a397, cudf commit SHA: https://github.com/rapidsai/cudf/commit/56150d9468862bce6c02be290f87d8d992986ceb

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 04a50c94c8691851d49303374f75f66cefc9a397, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/56150d9468862bce6c02be290f87d8d992986ceb
Test passed: **False**

**Comment by pxLi** [comment]
```
10:29:40  [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.012 s <<< FAILURE! - in com.nvidia.spark.rapids.jni.RowConversionTest
10:29:40  [ERROR] fixedWidthRowsRoundTrip  Time elapsed: 0.004 s  <<< FAILURE!
10:29:40  org.opentest4j.AssertionFailedError: Null Count For Column 0 ==> expected: <1> but was: <0>
10:29:40  	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
10:29:40  	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
10:29:40  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
10:29:40  	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:660)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertPartialColumnsAreEqual(AssertUtils.java:114)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertPartialColumnsAreEqual(AssertUtils.java:95)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertPartialTablesAreEqual(AssertUtils.java:250)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertTablesAreEqual(AssertUtils.java:260)
10:29:40  	at com.nvidia.spark.rapids.jni.RowConversionTest.fixedWidthRowsRoundTrip(RowConversionTest.java:86)
10:29:40  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:29:40  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:29:40  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:29:40  	at java.lang.reflect.Method.invoke(Method.java:498)
10:29:40  	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
10:29:40  	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
10:29:40  	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
10:29:40  	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
10:29:40  	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
10:29:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
10:29:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
10:29:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
10:29:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
10:29:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
10:29:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
10:29:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
10:29:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
10:29:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
10:29:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
10:29:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:155)
10:29:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:134)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
10:29:40  
10:29:40  [ERROR] fixedWidthRowsRoundTripWide  Time elapsed: 0.008 s  <<< FAILURE!
10:29:40  org.opentest4j.AssertionFailedError: Null Count For Column 0 ==> expected: <1> but was: <0>
10:29:40  	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
10:29:40  	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
10:29:40  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
10:29:40  	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:660)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertPartialColumnsAreEqual(AssertUtils.java:114)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertPartialColumnsAreEqual(AssertUtils.java:95)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertPartialTablesAreEqual(AssertUtils.java:250)
10:29:40  	at ai.rapids.cudf.AssertUtils.assertTablesAreEqual(AssertUtils.java:260)
10:29:40  	at com.nvidia.spark.rapids.jni.RowConversionTest.fixedWidthRowsRoundTripWide(RowConversionTest.java:53)
10:29:40  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:29:40  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:29:40  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:29:40  	at java.lang.reflect.Method.invoke(Method.java:498)
10:29:40  	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
10:29:40  	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
10:29:40  	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
10:29:40  	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
10:29:40  	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
10:29:40  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
10:29:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
10:29:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
10:29:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
10:29:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
10:29:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
10:29:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
10:29:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
10:29:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
10:29:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
10:29:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
10:29:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
10:29:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
10:29:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
10:29:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
10:29:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
10:29:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:155)
10:29:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:134)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
10:29:40  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
10:29:40  
10:29:40  [INFO] 
10:29:40  [INFO] Results:
10:29:40  [INFO] 
10:29:40  [ERROR] Failures: 
10:29:40  [ERROR]   RowConversionTest.fixedWidthRowsRoundTrip:86 Null Count For Column 0 ==> expected: <1> but was: <0>
10:29:40  [ERROR]   RowConversionTest.fixedWidthRowsRoundTripWide:53 Null Count For Column 0 ==> expected: <1> but was: <0>
10:29:40  [INFO] 
10:29:40  [ERROR] Tests run: 1273, Failures: 2, Errors: 0, Skipped: 3
```

**Comment by nvauto** [comment]
HEAD commit SHA: 04a50c94c8691851d49303374f75f66cefc9a397, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/56150d9468862bce6c02be290f87d8d992986ceb
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 4382c4ee339d10ebff9d87235e91fd77504bc458, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/132540e869e6866bcbfc749927e993989f83ecd2
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 97f64c4a000310cb8bbfde57153a9f3f9ce1219b, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/19554a1429c8516f73e91065ca03ff97ffff853f
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: aefc7994ae288dc3c01b72a7937f59b948cd582c, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/c4f471d43942f4f2777d09dce9912b019650c926
Test passed: **False**

**Comment by pxLi** [comment]
w/ https://github.com/NVIDIA/spark-rapids-jni/pull/1170 it passed the RowConversionTest.

now it failed CAST_STRING test
```
16:46:33  [INFO] Executing tasks
16:46:33  [INFO]      [exec] Running tests...
16:46:33  [INFO]      [exec] Test project /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/cmake-build
16:46:33  [INFO]      [exec]     Start 1: CAST_STRING
16:46:34  [INFO]      [exec] 1/2 Test #1: CAST_STRING ......................***Failed    0.94 sec
16:46:34  [INFO]      [exec]     Start 2: ROW_CONVERSION
16:46:56  [INFO]      [exec] 2/2 Test #2: ROW_CONVERSION ...................   Passed   19.12 sec
16:46:56  [INFO]      [exec] 
16:46:56  [INFO]      [exec] 50% tests passed, 1 tests failed out of 2
16:46:56  [INFO]      [exec] 
16:46:56  [INFO]      [exec] Total Test time (real) =  20.06 sec
16:46:56  [INFO]      [exec] 
16:46:56  [INFO]      [exec] The following tests FAILED:
16:46:56  [INFO]      [exec] 	  1 - CAST_STRING (Failed)
16:46:56  [INFO]      [exec] Errors while running CTest
16:46:56  [INFO]      [exec] Output from these tests are in: /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/cmake-build/Testing/Temporary/LastTest.log
16:46:56  [INFO]      [exec] Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
16:46:56  [INFO]      [exec] gmake: *** [Makefile:71: test] Error 8
16:46:56  [INFO] ------------------------------------------------------------------------
16:46:56  [INFO] BUILD FAILURE
16:46:56  [INFO] ------------------------------------------------------------------------
16:46:56  [INFO] Total time: 44:49.349s
16:46:56  [INFO] Finished at: Thu May 25 08:46:52 UTC 2023
16:46:56  [INFO] Final Memory: 42M/1367M
16:46:56  [INFO] ------------------------------------------------------------------------
16:46:56  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (test-sparkrapidsjni) on project spark-rapids-jni: An Ant BuildException has occured: exec returned: 2
16:46:56  [ERROR] around Ant part ...<exec failonerror="true" dir="/home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev" executable="cmake">... @ 4:121 in /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/target/antrun/build-main.xml
```

**Comment by nvauto** [comment]
HEAD commit SHA: 88851539e2db5917504bfc912d23e4bbd2e09a0d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/03f0c0cbd16a8681a5c723848858cb2af37d2a37
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: d1ea78a84cd6a21fb2d02d092dfd31602636707b, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/85699df8fac14358a83aa319dce9aa1400ae4f1e
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: d1ea78a84cd6a21fb2d02d092dfd31602636707b, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/85699df8fac14358a83aa319dce9aa1400ae4f1e
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 091d71b887c256d92aaf0a11c8b7badf2ea89c5e, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/85699df8fac14358a83aa319dce9aa1400ae4f1e
Test passed: **True**

**Comment by nvauto** [comment]
**SUCCESS** - auto-merge

**Pull request merged**
