### PR TITLE
add DOCKER_BUILD_EXTRA_ARGS and DOCKER_RUN_EXTRA_ARGS variable [skip ci]

### PR DESCRIPTION
**Pull request by wbo4958**
`./build/build-in-docker` is not working if vpn is enabled. And it's inconvenient to change script directly, So the PR add a DOCKER_NETWORKING to pass the network parameter, for example

```
DOCKER_NETWORKING="--network host" ./build/build-in-docker ...
```

### CODE REVIEW

**Review by jlowe — COMMENTED** [review]
Rather than add a very specific variable for a very specific docker argument (and thus likely we would end up adding another variable for another docker option to control later), why not have something more general like `DOCKER_EXTRA_ARGS`?

**Comment by wbo4958** [comment]
> Rather than add a very specific variable for a very specific docker argument (and thus likely we would end up adding another variable for another docker option to control later), why not have something more general like `DOCKER_EXTRA_ARGS`?

Thx @jlowe, done.

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by gerashegalov** [comment]
should host network be used by default for robustness?

**Pull request merged**
