### PR TITLE
Add guardword to hide cloud server info in pipeline

### PR DESCRIPTION
**Pull request by YanxuanLiu**
Add guardword to hide cloud server info in Pre-merge pipeline.

### CODE REVIEW

**Comment by YanxuanLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by YanxuanLiu** [comment]
> build

could you help to review the PR?

**Review by GaryShen2008 — APPROVED** [review]

**Comment by YanxuanLiu** [comment]
@GaryShen2008 could you help to merge the PR? Thanks!

**Pull request merged**
