### PR TITLE
Merge branch-24.12 into main 

### PR DESCRIPTION
**Pull request by nvauto**
Change version to 24.12.0

Note: merge this PR with **Create a merge commit to merge**

### CODE REVIEW

**Comment by YanxuanLiu** [comment]
build

**Comment by pxLi** [comment]
please never include header updates in merge to main, this should also be merged into 24.12 and 25.02
https://github.com/NVIDIA/spark-rapids-jni/pull/2672/commits/a0cfbf0820c59df045da703a3263e4fd7536a94b

please make a change to branch-24.12 first, and then upmerge this PR thanks

**Review by YanxuanLiu — COMMENTED** [review]
We added `license header check` github workflow in branch-24.12. It failed in https://github.com/NVIDIA/spark-rapids-jni/actions/runs/12251093908. Developers modified the files during branch-24.12 but did not update copyright header. Updated the copyright in a0cfbf0820c59df045da703a3263e4fd7536a94b

**Comment by YanxuanLiu** [comment]
> please never make header updates directly in merge to main, this should also be merged into 24.12 and 25.02 [a0cfbf0](https://github.com/NVIDIA/spark-rapids-jni/commit/a0cfbf0820c59df045da703a3263e4fd7536a94b)
> 
> please make a change to branch-24.12 first, and then upmerge this PR thanks

Sure, I'll make the modification in feature branch first.

**Comment by YanxuanLiu** [comment]
Need to update copyright header first, will create another PR then.

**Pull request closed without merging**
