### PR TITLE
[WIP] fix string to float using hand-picked values failed in CastOpSuite 

### PR DESCRIPTION
**Pull request by Feng-Jiang28**
https://github.com/NVIDIA/spark-rapids/issues/10986
## Rationales: 
https://github.com/NVIDIA/spark-rapids-jni/pull/2063 this pr has treated '+nan' as nan but spark treats as null. 
issue 10986 was caused by the reason above. 
This pr is for fixing it.

### CODE REVIEW

**Comment by thirtiseven** [comment]
build

**Comment by Feng-Jiang28** [comment]
build

**Review by thirtiseven — APPROVED** [review]
LGTM, pls test with plugin again before merging

**Comment by thirtiseven** [comment]
build

**Comment by Feng-Jiang28** [comment]
all UT and IT have passed.

**Comment by Feng-Jiang28** [comment]
build

**Pull request merged**
