### PR TITLE
Merge branch 'branch-23.12' into main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
As the title

**Note: please merge the PR with `Create a merge commit`**

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
This PR is not the final merge to main change.

Draft the PR for the advanced review purpose

 We'll up merge the cuDF commits after rapidsai get the v23.12.00 tagged/released.

**Review by jlowe — APPROVED** [review]

**Review by pxLi — APPROVED** [review]
Please merge as `create a merge request` thanks

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
build

**Pull request merged**
