### PR TITLE
Merge branch 'branch-23.04' into main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
NOTE: merge with `Create a merge commit` instead of squash

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by abellina** [comment]
@NvTimLiu one last for 23.04 https://github.com/NVIDIA/spark-rapids-jni/pull/1074, please monitor in case we merge.

**Review by pxLi — APPROVED** [review]
Please merge with `Create a merge commit`

**Comment by pxLi** [comment]
build

**Pull request merged**
