### PR TITLE
[submodule-sync] bot-submodule-sync-branch-24.04 to branch-24.04 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: a1ef9ee9f510652bebd83a6af49216d45f5b6adb, cudf commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: a1ef9ee9f510652bebd83a6af49216d45f5b6adb, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: a1ef9ee9f510652bebd83a6af49216d45f5b6adb, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: a1ef9ee9f510652bebd83a6af49216d45f5b6adb, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: a1ef9ee9f510652bebd83a6af49216d45f5b6adb, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: a1ef9ee9f510652bebd83a6af49216d45f5b6adb, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: a1ef9ee9f510652bebd83a6af49216d45f5b6adb, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 45df2bad339b5dd0a027f384ab40fa073fd6cf46, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 45df2bad339b5dd0a027f384ab40fa073fd6cf46, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/b47f5ee7d76e2382906adc351caff91b13801843
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 072b22ab7c980e8b828effea1c47587b664c8996, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/d5db68e018d720094489325d5547a7ed82f22b0d
Test passed: **False**

**Comment by jlowe** [comment]
Should pass on the next run.

**Pull request closed without merging**
