### PR TITLE
Copyright header check [skip ci]

### LINKED ISSUE #2571: [BUG] CI does not catch missing copyright or license on new files
One of the CI runs on #2559 should have failed due to a missing copyright and license header on a source file but it did not.  We should use something like apache-rat-plugin to catch this error of omission in CI.

### PR DESCRIPTION
**Pull request by YanxuanLiu**
fix #2571

Add github workflow `license-header-check` to check copyright/license header for files in Pull Request. 

A common action https://github.com/NVIDIA/spark-rapids-common/blob/main/license-header-check/action.yml is used for the check. The action requires an argument `included_file_patterns` for the scale of files to check. Users can also input argument `excluded_file_patterns` to exclude files based on included files. 

If files without copyright header `Copyright (c) .*, NVIDIA CORPORATION.` or with expired date exists, the workflow would return failed.

### CODE REVIEW

**Comment by pxLi** [comment]
the change looks good, 
but the failed action itself did not provide any useful info for debug https://github.com/NVIDIA/spark-rapids-jni/actions/runs/11907547850/job/33181412159?pr=2605

**Comment by YanxuanLiu** [comment]
> the change looks good, but the failed action itself did not provide any useful info for debug https://github.com/NVIDIA/spark-rapids-jni/actions/runs/11907547850/job/33181412159?pr=2605

I'll test in another PR and add some print info for debug to the common action.

**Comment by pxLi** [comment]
> > the change looks good, but the failed action itself did not provide any useful info for debug https://github.com/NVIDIA/spark-rapids-jni/actions/runs/11907547850/job/33181412159?pr=2605
> 
> I'll test in another PR and add some print info for debug to the common action.

sure, try test first against your JNI fork with branch-24.12 thanks

**Comment by pxLi** [comment]
seems the change did not cover scenarios like,
https://github.com/NVIDIA/spark-rapids-jni/blob/branch-24.12/src/main/fbs/profiler.fbs `*.fbs`
https://github.com/NVIDIA/spark-rapids-jni/blob/branch-24.12/ci/settings.xml `*.xml`
and folder for binaries like `build/*`

**Comment by YanxuanLiu** [comment]
> seems the change did not cover scenarios like, https://github.com/NVIDIA/spark-rapids-jni/blob/branch-24.12/src/main/fbs/profiler.fbs `*.fbs` https://github.com/NVIDIA/spark-rapids-jni/blob/branch-24.12/ci/settings.xml `*.xml` and folder for binaries like `build/*`

Thanks! Added these patterns.

**Review by pxLi — APPROVED** [review]
LGTM, please keep monitoring the PR check status of this repo. we can enable it as a required check when it performs stably

**Comment by YanxuanLiu** [comment]
build

**Pull request merged**
