### PR TITLE
Fix merge from 24.04 to 24.06

### PR DESCRIPTION
**Pull request by thirtiseven**
This PR resolves conflicts from https://github.com/NVIDIA/spark-rapids-jni/pull/1953

### CODE REVIEW

**Comment by thirtiseven** [comment]
build

**Comment by res-life** [comment]
LGTM for the get-json-object files.
I checked the get-json-object files, using exactly the files in branch-24.04 is correct.

**Review by res-life — DISMISSED** [review]

**Comment by res-life** [comment]
@NvTimLiu  Please double confirm this file: `.github/workflows/auto-merge.yml`

**Comment by thirtiseven** [comment]
this branch is break by some force push, created a new pr in https://github.com/NVIDIA/spark-rapids-jni/pull/1965

**Pull request closed without merging**
