### PR TITLE
[submodule-sync] bot-submodule-sync-branch-23.02 to branch-23.02 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
submodule-sync to create a PR keeping thirdparty/cudf up-to-date.
HEAD commit SHA: 28d84c45c410564a1520c038de65cacea0586fd0, cudf commit SHA: https://github.com/rapidsai/cudf/commit/9682fcac5458a73bec4b22a3d6222771eea1ee5a

This PR will be auto-merged if test passed. If failed, it will remain open until test pass or manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
HEAD commit SHA: 28d84c45c410564a1520c038de65cacea0586fd0, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/9682fcac5458a73bec4b22a3d6222771eea1ee5a
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: c3fc9e1e9d69d859d381a9596426f7e65dee133d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/77d1717744ecad904d9fe6ffc125db2be57e64e9
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: c3fc9e1e9d69d859d381a9596426f7e65dee133d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/77d1717744ecad904d9fe6ffc125db2be57e64e9
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: c3fc9e1e9d69d859d381a9596426f7e65dee133d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/77d1717744ecad904d9fe6ffc125db2be57e64e9
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: c3fc9e1e9d69d859d381a9596426f7e65dee133d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/77d1717744ecad904d9fe6ffc125db2be57e64e9
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: c3fc9e1e9d69d859d381a9596426f7e65dee133d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/77d1717744ecad904d9fe6ffc125db2be57e64e9
Test passed: **False**

**Comment by pxLi** [comment]
build error 
```
10:35:07  [INFO]      [exec] /opt/rh/devtoolset-9/root/usr/bin/ar qc ../../release/libparquet.a CMakeFiles/parquet_objlib.dir/arrow/path_internal.cc.o CMakeFiles/parquet_objlib.dir/arrow/reader.cc.o CMakeFiles/parquet_objlib.dir/arrow/reader_internal.cc.o CMakeFiles/parquet_objlib.dir/arrow/schema.cc.o CMakeFiles/parquet_objlib.dir/arrow/schema_internal.cc.o CMakeFiles/parquet_objlib.dir/arrow/writer.cc.o CMakeFiles/parquet_objlib.dir/bloom_filter.cc.o CMakeFiles/parquet_objlib.dir/column_reader.cc.o CMakeFiles/parquet_objlib.dir/column_scanner.cc.o CMakeFiles/parquet_objlib.dir/column_writer.cc.o CMakeFiles/parquet_objlib.dir/encoding.cc.o CMakeFiles/parquet_objlib.dir/encryption/encryption.cc.o CMakeFiles/parquet_objlib.dir/encryption/internal_file_decryptor.cc.o CMakeFiles/parquet_objlib.dir/encryption/internal_file_encryptor.cc.o CMakeFiles/parquet_objlib.dir/exception.cc.o CMakeFiles/parquet_objlib.dir/file_reader.cc.o CMakeFiles/parquet_objlib.dir/file_writer.cc.o CMakeFiles/parquet_objlib.dir/level_comparison.cc.o CMakeFiles/parquet_objlib.dir/level_conversion.cc.o CMakeFiles/parquet_objlib.dir/metadata.cc.o CMakeFiles/parquet_objlib.dir/murmur3.cc.o CMakeFiles/parquet_objlib.dir/__/generated/parquet_constants.cpp.o CMakeFiles/parquet_objlib.dir/__/generated/parquet_types.cpp.o CMakeFiles/parquet_objlib.dir/platform.cc.o CMakeFiles/parquet_objlib.dir/printer.cc.o CMakeFiles/parquet_objlib.dir/properties.cc.o CMakeFiles/parquet_objlib.dir/schema.cc.o CMakeFiles/parquet_objlib.dir/statistics.cc.o CMakeFiles/parquet_objlib.dir/stream_reader.cc.o CMakeFiles/parquet_objlib.dir/stream_writer.cc.o CMakeFiles/parquet_objlib.dir/types.cc.o CMakeFiles/parquet_objlib.dir/encryption/encryption_internal_nossl.cc.o
10:35:07  [INFO]      [exec] /opt/rh/devtoolset-9/root/usr/bin/ranlib ../../release/libparquet.a
10:35:07  [INFO]      [exec] [ 44%] Built target parquet_static
10:35:07  [INFO]      [exec] [ 44%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/dataset_writer.cc.o
10:35:07  [INFO]      [exec] [ 44%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/discovery.cc.o
10:35:07  [INFO]      [exec] [ 44%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/dataset.cc.o
10:35:07  [INFO]      [exec] [ 44%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_ipc.cc.o
10:35:07  [INFO]      [exec] [ 44%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_base.cc.o
10:35:07  [INFO]      [exec] [ 45%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/partition.cc.o
10:35:07  [INFO]      [exec] [ 45%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/plan.cc.o
10:35:07  [INFO]      [exec] [ 45%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_parquet.cc.o
10:35:07  [INFO]      [exec] [ 45%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/scanner.cc.o
10:35:07  [INFO]      [exec] [ 45%] Building CXX object _deps/arrow-build/src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/projector.cc.o
10:35:09  [INFO]      [exec] 1 error detected in the compilation of "/home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/thirdparty/cudf/cpp/src/binaryop/compiled/Greater.cu".
10:35:09  [INFO]      [exec] gmake[2]: *** [CMakeFiles/cudf.dir/build.make:258: CMakeFiles/cudf.dir/src/binaryop/compiled/Greater.cu.o] Error 1
10:35:09  [INFO]      [exec] 1 error detected in the compilation of "/home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-dev/thirdparty/cudf/cpp/src/binaryop/compiled/FloorDiv.cu".
10:35:09  [INFO]      [exec] gmake[2]: *** [CMakeFiles/cudf.dir/build.make:244: CMakeFiles/cudf.dir/src/binaryop/compiled/FloorDiv.cu.o] Error 1
10:35:19  [INFO]      [exec] gmake[1]: *** [CMakeFiles/Makefile2:814: CMakeFiles/cudf.dir/all] Error 2
10:35:19  [INFO]      [exec] gmake[1]: *** Waiting for unfinished jobs....
10:35:22  [INFO]      [exec] [ 45%] Built target arrow_dataset_objlib
10:35:22  [INFO]      [exec] gmake: *** [Makefile:156: all] Error 2
10:35:22  [INFO] ------------------------------------------------------------------------
10:35:22  [INFO] BUILD FAILURE
10:35:22  [INFO] ------------------------------------------------------------------------
```

**Comment by nvauto** [comment]
HEAD commit SHA: f2d521b51c02ca945f9ce7bb95f7e59ac394d445, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/ba5daec7efc6dbd26178561cf2a255bf69a0061a
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: aa385150f7b5e0d31cf8ce721a0484b52deb8f23, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/f8530da4a97db0c9a1d8247f5371565c2a57ebe2
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: aa385150f7b5e0d31cf8ce721a0484b52deb8f23, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/f8530da4a97db0c9a1d8247f5371565c2a57ebe2
Test passed: **False**

**Comment by jlowe** [comment]
Failure is in spdlog which was recently upgraded in rapidsai/rmm#1173
```
[INFO]      [exec] /spark-rapids-jni/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/fmt/bundled/core.h(426): error #186-D: pointless comparison of unsigned integer with zero
[INFO]      [exec]           detected during:
[INFO]      [exec]             instantiation of "auto fmt::v8::detail::to_unsigned(Int)->std::make_unsigned<Int>::type [with Int=size_t]" 
[INFO]      [exec] /spark-rapids-jni/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/fmt/bundled/format.h(458): here
[INFO]      [exec]             instantiation of "auto fmt::v8::detail::fill_n(T *, Size, char)->T * [with T=char, Size=size_t]" 
[INFO]      [exec] /spark-rapids-jni/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/fmt/bundled/format.h(702): here
[INFO]      [exec]             instantiation of "fmt::v8::basic_memory_buffer<T, SIZE, Allocator>::basic_memory_buffer(const Allocator &) [with T=char, SIZE=500UL, Allocator=std::allocator<char>]" 
[INFO]      [exec] /spark-rapids-jni/thirdparty/cudf/cpp/build/_deps/spdlog-src/include/spdlog/fmt/bundled/format-inl.h(85): here
[INFO]      [exec] 
[INFO]      [exec] 1 error detected in the compilation of "/spark-rapids-jni/thirdparty/cudf/cpp/src/binaryop/compiled/BitwiseXor.cu".
```

**Comment by nvauto** [comment]
HEAD commit SHA: 0a669e377f5cf5ee23704b31412cb17ca2176f2a, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/2048829ec66af1ceb7a9801702417d12ef13c77a
Test passed: **False**

**Comment by nvauto** [comment]
HEAD commit SHA: 60c9627c0efac3f17fd74b09ae924eb22645d34d, CUDF commit SHA: https://github.com/rapidsai/cudf/commit/1ca4dada8b66d21fe95ba7c31db2193c0bd2417a
Test passed: **True**

**Comment by nvauto** [comment]
**SUCCESS** - auto-merge

**Pull request merged**
