### PR TITLE
Trim C0 control chars in string to number type conversion

### PR DESCRIPTION
**Pull request by thirtiseven**
Closes https://github.com/NVIDIA/spark-rapids/issues/10724

In Spark, string to double will trim the string using [String.trim](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/lang/String.html), so it will trim characters equal to or less than '\u0020' (blank space).

This PR matches this behavior.

WIP for testing.

### CODE REVIEW

**Comment by thirtiseven** [comment]
Similar behavior also happens for int long and decimal. Updated code and tests.

**Comment by thirtiseven** [comment]
Local test code with plugin:
```
scala> val df = Seq(("1234\u0000"), ("\u00001234\u0000"), ("1234\u0000\u0000\u0000"), ("1000\u0001"), ("2000\u0002"), ("3000\u0003"), ("4000\u0004"), ("5000\u0005"), ("6000\u0006"), ("7000\u0007"), ("8000\u0008"), ("9000\u0009"), ("1000\u0010"), ("1100\u0011"), ("1200\u0012"), ("1300\u0013"), ("1300我"), ("1301\u0014"), ("1302\u0080"), ("1303\u0092"), ("1304\u009f"), ("1305\u001f")).toDF("value")
df: org.apache.spark.sql.DataFrame = [value: string]

scala> df.write.format("parquet").mode("overwrite").save("TEMP")
24/04/19 04:00:12 WARN GpuOverrides:
*Exec <DataWritingCommandExec> will run on GPU
  *Output <InsertIntoHadoopFsRelationCommand> will run on GPU
  *Exec <WriteFilesExec> will run on GPU
    ! <LocalTableScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.LocalTableScanExec
      @Expression <AttributeReference> value#4 could run on GPU


scala> val df = spark.read.parquet("TEMP")
df: org.apache.spark.sql.DataFrame = [value: string]

scala> df.selectExpr("value", "length(value)", "cast(value as int)").show(false)
24/04/19 04:00:23 WARN GpuOverrides:
!Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
  @Partitioning <SinglePartition$> could run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> cast(length(value#7) as string) AS length(value)#19 will run on GPU
      *Expression <Cast> cast(length(value#7) as string) will run on GPU
        *Expression <Length> length(value#7) will run on GPU
    *Expression <Alias> cast(cast(value#7 as int) as string) AS value#20 will run on GPU
      *Expression <Cast> cast(cast(value#7 as int) as string) will run on GPU
        *Expression <Cast> cast(value#7 as int) will run on GPU
    *Exec <FileSourceScanExec> will run on GPU

+-------+-------------+-----+
|value  |length(value)|value|
+-------+-------------+-----+
|1234|7            |1234 |
|1000  |5            |1000 |
|2000  |5            |2000 |
|1300我 |5            |null |
|1301  |5            |1301 |
|1302  |5            |null |
|3000  |5            |3000 |
|4000  |5            |4000 |
|5000  |5            |5000 |
|6000  |5            |6000 |
|7000\a |5            |7000 |
|8000\b |5            |8000 |
|1100  |5            |1100 |
|1200  |5            |1200 |
|1300  |5            |1300 |
|1303  |5            |null |
|1304  |5            |null |
|1305  |5            |1305 |
|9000\t |5            |9000 |
|1000  |5            |1000 |
+-------+-------------+-----+
only showing top 20 rows


scala> df.selectExpr("value", "length(value)", "cast(value as decimal)").show(false)
24/04/19 04:00:29 WARN GpuOverrides:
!Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
  @Partitioning <SinglePartition$> could run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> cast(length(value#7) as string) AS length(value)#37 will run on GPU
      *Expression <Cast> cast(length(value#7) as string) will run on GPU
        *Expression <Length> length(value#7) will run on GPU
    *Expression <Alias> cast(cast(value#7 as decimal(10,0)) as string) AS value#38 will run on GPU
      *Expression <Cast> cast(cast(value#7 as decimal(10,0)) as string) will run on GPU
        *Expression <Cast> cast(value#7 as decimal(10,0)) will run on GPU
    *Exec <FileSourceScanExec> will run on GPU

+-------+-------------+-----+
|value  |length(value)|value|
+-------+-------------+-----+
|1234|7            |1234 |
|1000  |5            |1000 |
|2000  |5            |2000 |
|1300我 |5            |null |
|1301  |5            |1301 |
|1302  |5            |null |
|3000  |5            |3000 |
|4000  |5            |4000 |
|5000  |5            |5000 |
|6000  |5            |6000 |
|7000\a |5            |7000 |
|8000\b |5            |8000 |
|1100  |5            |1100 |
|1200  |5            |1200 |
|1300  |5            |1300 |
|1303  |5            |null |
|1304  |5            |null |
|1305  |5            |1305 |
|9000\t |5            |9000 |
|1000  |5            |1000 |
+-------+-------------+-----+
only showing top 20 rows


scala> spark.conf.set("spark.rapids.sql.enabled", false)

scala> df.selectExpr("value", "length(value)", "cast(value as int)").show(false)
+-------+-------------+-----+
|value  |length(value)|value|
+-------+-------------+-----+
|1234|7            |1234 |
|1000  |5            |1000 |
|2000  |5            |2000 |
|1300我 |5            |null |
|1301  |5            |1301 |
|1302  |5            |null |
|3000  |5            |3000 |
|4000  |5            |4000 |
|5000  |5            |5000 |
|6000  |5            |6000 |
|7000\a |5            |7000 |
|8000\b |5            |8000 |
|1100  |5            |1100 |
|1200  |5            |1200 |
|1300  |5            |1300 |
|1303  |5            |null |
|1304  |5            |null |
|1305  |5            |1305 |
|9000\t |5            |9000 |
|1000  |5            |1000 |
+-------+-------------+-----+
only showing top 20 rows

scala> df.selectExpr("value", "length(value)", "cast(value as decimal)").show(false)
+-------+-------------+-----+
|value  |length(value)|value|
+-------+-------------+-----+
|1234|7            |1234 |
|1000  |5            |1000 |
|2000  |5            |2000 |
|1300我 |5            |null |
|1301  |5            |1301 |
|1302  |5            |null |
|3000  |5            |3000 |
|4000  |5            |4000 |
|5000  |5            |5000 |
|6000  |5            |6000 |
|7000\a |5            |7000 |
|8000\b |5            |8000 |
|1100  |5            |1100 |
|1200  |5            |1200 |
|1300  |5            |1300 |
|1303  |5            |null |
|1304  |5            |null |
|1305  |5            |1305 |
|9000\t |5            |9000 |
|1000  |5            |1000 |
+-------+-------------+-----+
only showing top 20 rows
```

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by thirtiseven** [comment]
build

**Comment by thirtiseven** [comment]
build

**Pull request merged**
